[package]
name = "enum_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
any_ascii = "0.3.3"
deunicode = "1.6.2"
enum_dispatch = "0.3.13"
hanconv = "0.5.0"
hangeul = "0.4.0"
itertools = "0.14.0"
lazy_static = "1.5.0"
mecab = "0.1.6"
pinyin = "0.11.0"
pinyin_zhuyin = "0.2.0"
rayon = "1.11.0"
regex = "1.12.2"
serde = { version = "1.0" , features = ["derive"] }
serde-aux = "4.7.0"
serde_json = "1.0.149"
unicode-blocks = "0.1.9"
unidecode = "0.3.0"
wana_kana = "4.0.0"

