#!/usr/bin/env python3
import os
import shutil
import pathlib

def get_tmpdir_path():
    ppid = os.getppid()
    env_path = os.environ.get("POLLINGUA_COMPLETION_RUNTIME_TMPFILE_PATH")
    if env_path:
        return pathlib.Path(env_path)
    xdg_runtime_dir = os.environ.get("XDG_RUNTIME_DIR")
    if xdg_runtime_dir:
        return pathlib.Path(xdg_runtime_dir) / f".{ppid}_polingua_tmp"
    return pathlib.Path(f"/tmp/.{ppid}_polingua_tmp")

def main():
    target_dir = get_tmpdir_path()
    if target_dir.exists() and target_dir.is_dir():
        #try:
        shutil.rmtree(target_dir)
            #print(f"Successfully removed: {target_dir}")
        #except Exception as e:
            #print(f"Error while deleting {target_dir}: {e}")
    #else:
    #    print(f"Directory not found, skipping: {target_dir}")

if __name__ == "__main__":
    main()
